### ISSUE TITLE
Create empty project in .net 6

### ISSUE THREAD

**Issue by JrogeT** [jroge-uagrm/CriselitoComic-backend#9]
Delete all files in repo and upload new code

**Comment by cbcrisel** [comment]
![image](https://user-images.githubusercontent.com/61096663/138954433-9aeb8913-9126-41e8-bed3-69de292f460c.png)

**Comment by JrogeT** [comment]
Open merge request pls

**Comment by cbcrisel** [comment]
![image](https://user-images.githubusercontent.com/61096663/138957937-6bd06463-cee9-42f0-8908-1ce09662ad39.png)
